tic = Sys.time()
cat("Running script './code/utility/Figure_1.R'...")
source("./code/utility/Figure_1.R")
cat("Done. Figure_1.pdf saved in 'results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_2.R'...")
source("./code/utility/Figure_2.R")
cat("Done. Figure_2.pdf saved in 'results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_3.R'...")
source("./code/utility/Figure_3.R")
cat("Done. Figure_3.pdf saved in 'results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_4.R'...")
source("./code/utility/Figure_4.R")
cat("Done. Figure_4.pdf saved in 'results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_5_1.R'...")
source("./code/utility/Figure_5_1.R")
cat("Done. Figure_5_1.Rds saved in 'data/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_5_2.R'...")
source("./code/utility/Figure_5_2.R")
cat("Done. Figure_5_2.Rds saved in 'data/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_5_3.R'...")
source("./code/utility/Figure_5_3.R")
cat("Done. Figure_5_3.Rds saved in 'data/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_5_all.R'...")
source("./code/utility/Figure_5_all.R")
cat("Done. Figure_5.pdf saved in 'results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_A1.R'...")
source("./code/utility/Figure_A1.R")
cat("Done. Figure_A1.pdf saved in './results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_A2.R'...")
source("./code/utility/Figure_A2.R")
cat("Done. Figure_A2.pdf saved in './results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_A3_1.R'...")
source("./code/utility/Figure_A3_1.R")
cat("Done. Figure_A3_1.Rds saved in './data/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_A3_2.R'...")
source("./code/utility/Figure_A3_2.R")
cat("Done. Figure_A3_2.Rds saved in './data/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_A3_3.R'...")
source("./code/utility/Figure_A3_3.R")
cat("Done. Figure_A3_3.Rds saved in './data/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())

tic = Sys.time()
cat("Running script './code/utility/Figure_A3_all.R'...")
source("./code/utility/Figure_A3_all.R")
cat("Done. Figure_A3.pdf saved in './results/'.\n")
toc = Sys.time()
print(toc - tic)
rm(list = ls())
