tic = Sys.time()
cat("Runing script 'R/utility/Figure_1.R'...")
source("./R/utility/Figure_1.R")
cat("Done. Figure_1.pdf saved in 'figures/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_2.R'...")
source("./R/utility/Figure_2.R")
cat("Done. Figure_2.pdf saved in 'figures/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_3.R'...")
source("./R/utility/Figure_3.R")
cat("Done. Figure_3.pdf saved in 'figures/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_4.R'...")
source("./R/utility/Figure_4.R")
cat("Done. Figure_4.pdf saved in 'figures/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_5_1.R'...")
source("./R/utility/Figure_5_1.R")
cat("Done. Figure_5_1.Rds saved in 'data/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_5_2.R'...")
source("./R/utility/Figure_5_2.R")
cat("Done. Figure_5_2.Rds saved in 'data/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_5_3.R'...")
source("./R/utility/Figure_5_3.R")
cat("Done. Figure_5_3.Rds saved in 'data/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script 'R/utility/Figure_5_all.R'...")
source("./R/utility/Figure_5_all.R")
cat("Done. Figure_5.pdf saved in 'figures/'.\n")
toc = Sys.time()
print(toc - tic)
