tic = Sys.time()
cat("Runing script './code/utility/Figure_A1.R'...")
source("./code/utility/Figure_A1.R")
cat("Done. Figure_A1.pdf saved in './results/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script './code/utility/Figure_A2.R'...")
source("./code/utility/Figure_A2.R")
cat("Done. Figure_A2.pdf saved in './results/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script './code/utility/Figure_A3_1.R'...")
source("./code/utility/Figure_A3_1.R")
cat("Done. Figure_A3_1.Rds saved in './data/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script './code/utility/Figure_A3_2.R'...")
source("./code/utility/Figure_A3_2.R")
cat("Done. Figure_A3_2.Rds saved in './data/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script './code/utility/Figure_A3_3.R'...")
source("./code/utility/Figure_A3_3.R")
cat("Done. Figure_A3_3.Rds saved in './data/'.\n")
toc = Sys.time()
print(toc - tic)

tic = Sys.time()
cat("Runing script './code/utility/Figure_A3_all.R'...")
source("./code/utility/Figure_A3_all.R")
cat("Done. Figure_A3.pdf saved in './results/'.\n")
toc = Sys.time()
print(toc - tic)
